if [[ -n $(git status --porcelain) ]]; then
  echo "Changes detected. Committing and pushing."
  git config --global user.name 'Sircjarr'
  git config --global user.email 'Sircjarr@users.noreply.github.com'
  git add .
  git commit -m "Autogenerated JaCoCo coverage badge"
  git push
else
  echo "No changes detected. No action taken."
fi